In [1]:
from numpy import linalg as LA
import numpy as np

In [3]:
w,v = LA.eig(np.array([[-2, 1],[1,-1]]))
w,v

(array([-2.61803399, -0.38196601]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]),
 array([[-2,  1],
        [ 1, -1]]))